#!/bin/bash
#cat nasa_19950801.tsv | cut -d "	" -f 1 | uniq -u | tail -n 11 | sort -nr | cut -d "	" -f 1

#cat nasa_19950801.tsv | cut -d "	" -f 1 #| uniq -u | tail -n 11 | sort -r

cat nasa_19950801.tsv | tail -n 11 | cut -d "	" -f 3 | sort -n 
