#!/usr/bin/env bash
# Write a Bash script that groups visitors by IP and HTTP status code, and displays this data.
cut -d " " -f 1,9 apache-access.log | awk '{print}' | uniq -c | sort -g | tac | uniq -u
