#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and do some stuff
i=1
while (( i < 11 ))
do 
	if (( i == 4))
	then
		echo 'bad luck'
		(( i++ ))
	elif (( i == 8))
	then	
	       echo 'good luck'
	       (( i++ ))
        else
		echo 'Best School'
		(( i++ ))
	fi
done 
