#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes
h=0
m=1
while (( h < 13 )) 
do 
	echo "Hour: $h"
	while (( m < 60 ))
	do
		echo "$m"
		(( m++ ))
	done
	m=1
	(( h++ ))
done
