#!/usr/bin/env bash
# Write a Bash script that displays some stuff
i="$( find . -maxdepth 1 -name '*' | wc -l )"
for _ in $i 
do 
	find . -maxdepth 1 -name '*' | tr "	" "\n" | rev | cut -d "-" -f 1 | rev
done

