#!/usr/bin/env bash
# Write a Bash script that do some stuff 


echo "$$" > /var/run/myscript.pid
while true 
do 
	echo 'To infinity and beyond' 
	trap 'echo I hate the kill command' 15
	trap 'echo Y U no love me?' 2
	trap 'rm /var/run/myscript.pid' 3 15
	trap 'pkill -9 -f 10-process_and_pid_file' 3 15 
done 
