#!/usr/bin/env bash
# Write a Bash script that do some stuff 


echo "$$" > /var/run/myscript.pid
while true 
do 
	echo 'To infinity and beyond' 
	trap 'echo I hate the kill command | rm /var/run/myscript.pid | sudo pkill -9 10-process_and_pid_file' SIGTERM
	trap 'echo Y U no love me?' SIGINT
	trap 'rm /var/run/myscript.pid | sudo pkill -9 10-process_and_pid_file' SIGQUIT
	sleep 2	
done 
