#!/usr/bin/env bash
# a
echo "$$" > /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; pkill -9 -f '10-process_and_pid_file' " SIGTERM
trap "rm /var/run/myscript.pid; pkill -9 -f '10-process_and_pid_file'" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true 
do
	echo "To infinity and beyond"
	sleep 2
done
