#!/usr/bin/env bash
#Write a manage_my_process Bash script that: do some stuff 
if [ -n "$1" ]
then 
	if [ "$1" == "start" ]  
		then
			./manage_my_process & echo "$!" > "/var/run/my_process.pid" & echo 'manage_my_process started' ;
		
	elif [ "$1" == "stop" ]
		then
			pkill -f /var/run/my_process.pid & rm "/var/run/my_process.pid" & echo 'manage_my_process stopped' ;

	elif [ "$1" == "restart" ]
		then 
			pkill -f /var/run/my_process.pid & rm "/var/run/my_process.pid" & sudo ./manage_my_process & echo "$$" > '/var/run/my_process.pid' & echo 'manage_my_process restarted' ;

		else 
			echo 'Usage: manage_my_process {start|stop|restart}' ;

	fi

else 
	echo 'Usage: manage_my_process {start|stop|restart}' ;
fi
